// <auto-generated />
using System;
using Lumen.Authorization.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumen.Authorization.Migrations.EfMigrations
{
    [DbContext(typeof(LumenAuthorizationDbContext))]
    [Migration("20260706000000_AddScopeIdToUserProfile")]
    partial class AddScopeIdToUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Authorization.Domain.GroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_permission_group_name_unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PermissionGroup", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("GroupPermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrphan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrphanedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_permission_code_unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("GroupPermissionId");

                    b.ToTable("Permission", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.PermissionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_lumen_permission_profile_permission_id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("PermissionId", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_permission_profile_active_unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PermissionProfile", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_profile_name_unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Profile", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lumen_user_profile_user_id");

                    b.HasIndex("UserId", "ProfileId", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_user_profile_active_unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("UserProfile", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.Permission", b =>
                {
                    b.HasOne("Lumen.Authorization.Domain.GroupPermission", null)
                        .WithMany()
                        .HasForeignKey("GroupPermissionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.PermissionProfile", b =>
                {
                    b.HasOne("Lumen.Authorization.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumen.Authorization.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.UserProfile", b =>
                {
                    b.HasOne("Lumen.Authorization.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
