// <auto-generated />
using System;
using Lumen.Authorization.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Authorization.Migrations.PostgreSQL.EfMigrations
{
    [DbContext(typeof(LumenAuthorizationDbContext))]
    partial class LumenAuthorizationPostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Authorization.Domain.GroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_permission_group_name_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("PermissionGroup", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("GroupPermissionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrphan")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OrphanedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_permission_code_unique")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("GroupPermissionId")
                        .HasDatabaseName("IX_Permission_GroupPermissionId");

                    b.ToTable("Permission", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.PermissionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_lumen_permission_profile_permission_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("IX_PermissionProfile_ProfileId");

                    b.HasIndex("PermissionId", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_permission_profile_active_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("PermissionProfile", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_profile_name_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Profile", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("IX_UserProfile_ProfileId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lumen_user_profile_user_id");

                    b.HasIndex("UserId", "ProfileId", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ix_lumen_user_profile_active_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("UserProfile", "Lumen");
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.Permission", b =>
                {
                    b.HasOne("Lumen.Authorization.Domain.GroupPermission", null)
                        .WithMany()
                        .HasForeignKey("GroupPermissionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.PermissionProfile", b =>
                {
                    b.HasOne("Lumen.Authorization.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumen.Authorization.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Authorization.Domain.UserProfile", b =>
                {
                    b.HasOne("Lumen.Authorization.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
